# Generated by Django 3.2.4 on 2021-06-26 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
